int consume(int code);
int unit();
int declStruct();
int declVar();
int declFunc();
int typeBase();
int arrayDecl();
int typeName();
int funcArg();
int stmCompound();
int stm();
int expr();
int exprAssign();
int exprUnary();
int exprOr();
int exprOrPrim();
int exprAnd();
int exprAndPrim();
int exprEq();
int exprEqPrim();
int exprRel();
int exprRelPrim();
int exprRelSecond();
int exprAdd();
int exprAddPrim();
int exprMul();
int exprMulPrim();
int exprCast();
int exprPostfix();
int exprPostfixPrim();
int exprPrimary();
Symbol *findSymbol(Symbols *symbols, const char *name);
void deleteSymbolsAfter(Symbols *symbols, Symbol *start);
Symbol *addSymbol(Symbols *symbols, const char *name, int cls);
void initSymbols(Symbols *symbols);
void addVar(Token *tkName, Type *t);